//-----------------------------------------------------------------------------
// Copyright (c) 2011-2014, Fusion-io, Inc. (acquired by SanDisk Corp. 2014)
// Copyright (c) 2014-2015, SanDisk Corp. and/or all its affiliates.
// All rights reserved.
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
// * Redistributions of source code must retain the above copyright notice,
//   this list of conditions and the following disclaimer.
// * Redistributions in binary form must reproduce the above copyright notice,
//   this list of conditions and the following disclaimer in the documentation
//   and/or other materials provided with the distribution.
// * Neither the name of the SanDisk Corp. nor the names of its contributors
//   may be used to endorse or promote products derived from this software
//   without specific prior written permission.
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
// OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//-----------------------------------------------------------------------------

#ifndef _FIO_PORT_LINUX_KFIO_CONFIG_H_
#define _FIO_PORT_LINUX_KFIO_CONFIG_H_

#define KFIOC_MISSING_WORK_FUNC_T (0)
#define KFIOC_WORKDATA_PASSED_IN_WORKSTRUCT (1)
#define KFIOC_HAS_PCI_ERROR_HANDLERS (1)
#define KFIOC_HAS_GLOBAL_REGS_POINTER (1)
#define KFIOC_HAS_SYSRQ_KEY_OP_ENABLE_MASK (1)
#define KFIOC_HAS_DISK_STATS_READ_WRITE_ARRAYS (1)
#define KFIOC_HAS_LINUX_SCATTERLIST_H (1)
#define KFIOC_KMEM_CACHE_CREATE_REMOVED_DTOR (1)
#define KFIOC_BIO_ENDIO_REMOVED_BYTES_DONE (1)
#define KFIOC_INVALIDATE_BDEV_REMOVED_DESTROY_DIRTY_BUFFERS (1)
#define KFIOC_NEEDS_VIRT_TO_PHYS (0)
#define KFIOC_HAS_BLK_UNPLUG (0)
#define KFIOC_HAS_BLK_DELAY_QUEUE (1)
#define KFIOC_REQUEST_QUEUE_HAS_UNPLUG_FN (0)
#define KFIOC_REQUEST_QUEUE_UNPLUG_FN_HAS_EXTRA_BOOL_PARAM (1)
#define KFIOC_BACKING_DEV_INFO_HAS_UNPLUG_IO_FN (0)
#define KFIOC_HAS_KMEM_CACHE (1)
#define KFIOC_HAS_MUTEX_SUBSYSTEM (1)
#define KFIOC_STRUCT_FILE_HAS_PATH (0)
#define KFIOC_HAS_PATH_LOOKUP (0)
#define KFIOC_UNREGISTER_BLKDEV_RETURNS_VOID (1)
#define KFIOC_PARTITION_STATS (1)
#define KFIOC_HAS_NEW_BLOCK_METHODS (1)
#define KFIOC_BLOCK_DEVICE_RELEASE_RETURNS_INT (0)
#define KFIOC_HAS_NEW_BLKDEV_METHODS (1)
#define KFIOC_HAS_COMPAT_IOCTL_METHOD (1)
#define KFIOC_COMPAT_IOCTL_RETURNS_LONG (1)
#define KFIOC_DISCARD (1)
#define KFIOC_DISCARD_ZEROES_IN_LIMITS (1)
#define KFIOC_HAS_REQ_UNPLUG (0)
#define KFIOC_HAS_BIO_RW_SYNC (0)
#define KFIOC_HAS_BIO_RW_UNPLUG (0)
#define KFIOC_HAS_BIOVEC_ITERATORS (1)
#define KFIOC_DISCARD_GRANULARITY_IN_LIMITS (1)
#define KFIOC_BARRIER (0)
#define KFIOC_USE_LINUX_UACCESS_H (1)
#define KFIOC_HAS_SPIN_LOCK_IRQSAVE_NESTED (1)
#define KFIOC_MODULE_PARAM_ARRAY_NUMP (1)
#define KFIOC_OWNER_IN_STRUCT_PROC_DIR_ENTRY (0)
#define KFIOC_CONFIG_PREEMPT_RT (0)
#define KFIOC_CONFIG_TREE_PREEMPT_RCU (0)
#define KFIOC_HAS_BLK_QUEUE_HARDSECT_SIZE (0)
#define KFIOC_HAS_END_REQUEST (0)
#define KFIOC_USE_IO_SCHED (1)
#define KFIOC_USE_NEW_IO_SCHED (1)
#define KFIOC_HAS_ELV_DEQUEUE_REQUEST (0)
#define KFIOC_HAS_BIO_RW_FLAGGED (0)
#define KFIOC_HAS_INFLIGHT_RW (0)
#define KFIOC_HAS_INFLIGHT_RW_ATOMIC (1)
#define KFIOC_HAS_BLK_LIMITS_IO_MIN (1)
#define KFIOC_HAS_BLK_LIMITS_IO_OPT (1)
#define KFIOC_HAS_BLK_QUEUE_MAX_SEGMENTS (1)
#define KFIOC_HAS_UNIFIED_BLKTYPES (1)
#define KFIOC_HAS_BIO_RW_DISCARD (0)
#define KFIOC_SYSRQ_HANDLER_NEEDS_TTY_STRUCT (0)
#define KFIOC_PCI_REQUEST_REGIONS_CONST_CHAR (1)
#define KFIOC_FOPS_USE_LOCKED_IOCTL (0)
#define KFIOC_HAS_RQ_POS_BYTES (1)
#define KFIOC_HAS_RQ_IS_SYNC (1)
#define KFIOC_HAS_RQ_FOR_EACH_BIO (1)
#define KFIOC_HAS_REQ_RW_SYNC (0)
#define KFIOC_BIOSET_CREATE_HAS_THIRD_ARG (0)
#define KFIOC_QUEUE_HAS_NONROT_FLAG (1)
#define KFIOC_QUEUE_HAS_RANDOM_FLAG (1)
#define KFIOC_KBLOCKD_SCHEDULE_HAS_QUEUE_ARG (0)
#define KFIOC_TASK_HAS_NR_CPUS_ALLOWED (0)
#define KFIOC_TASK_HAS_BOUND_FLAG (0)
#define KFIOC_NUMA_MAPS (1)
#define KFIOC_PCI_HAS_NUMA_INFO (1)
#define KFIOC_CACHE_ALLOC_NODE_TAKES_FLAGS (1)
#define KFIOC_NEW_BARRIER_SCHEME (1)
#define KFIOC_HAS_QUEUE_FLAG_CLUSTER (0)
#define KFIOC_HAS_QUEUE_LIMITS_CLUSTER (1)
#define KFIOC_HAS_QUEUE_FLAG_CLEAR_UNLOCKED (0)
#define KFIOC_HAS_BIO_COMP_CPU (0)
#define KFIOC_BVEC_KMAP_IRQ_HAS_LONG_FLAGS (1)
#define KFIOC_MAKE_REQUEST_FN_VOID (1)
#define KFIOC_HAS_BLK_FS_REQUEST (0)
#define KFIOC_KMAP_ATOMIC_NEEDS_TYPE (0)
#define KFIOC_HAS_BLK_ALLOC_QUEUE_NODE (1)
#define KFIOC_SGLIST_NEW_API (1)
#define KFIOC_HAS_PROCFS_PDE_DATA (1)
#define KFIOC_HAS_PROC_CREATE_DATA (1)
#define KFIOC_HAS_NEW_QUEUECOMMAND_SIGNATURE (1)
#define KFIOC_HAS_SCSI_SG_FNS (1)
#define KFIOC_HAS_SCSI_SG_COPY_FNS (1)
#define KFIOC_HAS_SCSI_RESID_FNS (1)
#define KFIOC_BIO_HAS_HW_SEGMENTS (0)
#define KFIOC_BIO_HAS_SEG_SIZE (0)
#define KFIOC_BIO_HAS_DESTRUCTOR (0)
#define KFIOC_BIO_HAS_ATOMIC_REMAINING (0)
#define KFIOC_BIO_HAS_INTEGRITY (0)
#define KFIOC_BIO_HAS_SPECIAL (0)
#include <linux/slab.h>
#include <linux/gfp.h>

#ifndef GFP_NOWAIT
#define GFP_NOWAIT  (GFP_ATOMIC & ~__GFP_HIGH)
#endif

#endif /* _FIO_PORT_LINUX_KFIO_CONFIG_H_ */
