#!/bin/sh
set -e
# Automatically added by dh_installmodules
if [ "$1" = "configure" ]; then
	if [ -e /boot/System.map-3.16.0-41-generic ]; then
		depmod -a -F /boot/System.map-3.16.0-41-generic 3.16.0-41-generic || true
	fi
fi
# End automatically added section
